[package]
name = "tcp-echo-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42", features = ["full"] }
socket2 = "0.6.1"
num_cpus = "1.17.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

